import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=p=>JSON.parse(readFileSync(new URL(p,import.meta.url),'utf8'));
const pre=read('./pretest.json');
const rde=read('../representative-device-evidence-readiness/acceptance-contract.json');
const phys=read('../representative-device-physical-autopilot/protocol.json');
assert.equal(pre.schema,'FAE_IPAD_UNIFIED_PRETEST_MI_V1');
assert.equal(pre.authority,'CANDIDATE_PRETEST_ONLY_NO_PHYSICAL_DISPATCH');
assert.equal(rde.contract_id,pre.source_refs.rde_contract);
assert.equal(phys.protocol_id,pre.source_refs.rde_autopilot);
assert.equal(rde.source_binding.baseline_source_revision,pre.source_refs.tested_source_revision);
assert.equal(phys.source_binding.tested_miner_blob_sha,pre.source_refs.tested_miner_blob_sha);
assert.equal(rde.coverage_contract.minimum_required_classes,4);
assert.deepEqual(rde.coverage_contract.required_class_ids,['mobile_tablet_arm','thin_light_integrated','consumer_discrete_gpu','compact_handheld_consumer']);
const w=rde.workload_protocol;
assert.equal(w.pure_mining_sustained.repetitions,3);
assert.equal(w.normal_use_coexistence.repetitions,3);
const duration=3*(w.pure_mining_sustained.warmup_seconds+w.pure_mining_sustained.measurement_seconds)+3*(phys.campaign.normal_use_coexistence.baseline_seconds+w.normal_use_coexistence.warmup_seconds+w.normal_use_coexistence.measurement_seconds);
assert.equal(duration,9180);
assert.equal(pre.campaign.rde_timed_seconds,duration);
assert.equal(phys.campaign.lifecycle_recovery.minimum_hidden_visible_cycles,5);
assert.equal(pre.campaign.hfb_official_min_seconds,1800);
assert.equal(pre.campaign.hfb_preferred_seconds,2100);
assert.equal(pre.campaign.mts_residual_gate_ms,1500);
assert.equal(pre.campaign.nominal_nonoverlap_seconds,9180+2100);
const mi=pre.maximum_inference;
assert.equal(mi.targets.length,3);
for(const t of mi.targets){
  assert.ok(t.model_paths.length>=2,t.id);
  for(const f of ['assumption_refs','counterfactuals','failure_signatures','discriminating_measurements','reality_gap']) {
    assert.ok((t[f]??mi.common_assumptions)?.length>0,t.id+' '+f);
  }
  assert.equal(t.material_reality_gap,true);
  assert.ok(t.prediction_bands.length>=1,t.id);
  for(const b of t.prediction_bands)assert.ok(b.low<=b.nominal&&b.nominal<=b.high);
}
assert.ok(mi.interpretation_rules.length>=3);
for(const k of ['simulation_evidence_only']) assert.equal(mi[k],true);
for(const k of ['empirical_validation_claimed','authority_created','execution_triggered'])assert.equal(mi[k],false);
assert.equal(pre.readiness.all_three_one_click_ready,false);
assert.equal(pre.readiness.mts_v3_residual_only_ready,false);
assert.equal(pre.readiness.mts_v3_public_access_verified,false);
assert.equal(pre.readiness.live_hardware_measurements_performed,false);
assert.equal(rde.historical_evidence_policy.MTS12_is_representative_device_evidence,false);
assert.equal(rde.historical_evidence_policy.ASIC_lab_is_representative_device_evidence,false);
assert.equal(rde.run_acceptance.sustained_throughput_retention_minimum,.7);
assert.equal(rde.metrics.normal_use.maximum_p95_ratio_for_supported_class,2);
assert.equal(rde.workload_protocol.lifecycle_recovery.minimum_transitions,5);
assert.equal(phys.physical_mode.synthetic_events_allowed,false);
assert.equal(phys.physical_mode.duration_scaling_allowed,false);
const mts=readFileSync(new URL('../mining-tip-sync/mts-12-ipad-acceptance.html',import.meta.url),'utf8');
assert.ok(mts.includes('const RESUME_GATE_MS=1500'));
assert.ok(mts.includes('foreground_event_to_authoritative_status_request_start'));
assert.ok(mts.includes('if(!RESIDUAL_ONLY&&!state.tipVerdict?.pass)'), 'Full V3 still requires real-tip PASS; only opt-in residual bypasses');
assert.ok(mts.includes("const RESIDUAL_ONLY=new URLSearchParams(location.search).get('residualOnly')==='1'"));
assert.ok(mts.includes('HISTORICAL_TIP_EVIDENCE_SHA256'));
assert.ok(mts.includes('FAE_MTS_12_PHYSICAL_IPAD_RESIDUAL_V3'));
assert.ok(mts.includes("'RESIDUAL_PASS__HISTORICAL_TIP_NOT_RETESTED'"));
assert.ok(mts.includes('FAE_MTS_12_PHYSICAL_IPAD_EVIDENCE_V3'));
const described=['no new paid spend','no physical dispatch','no synthetic evidence'];
console.log(JSON.stringify({verdict:'PRETEST_CONTRACT_VERIFIED__PHYSICAL_STILL_REQUIRED__MTS_V3_RESIDUAL_HOST_GATE',contract:rde.contract_id,exact_miner_blob:pre.source_refs.tested_miner_blob_sha,timed_rde_seconds:duration,hfb_preferred_seconds:2100,combined_fixed_seconds:duration+2100,mts_v3_public_access:false,physical_pass:false,notes:described},null,2));
