// FAE public testnet v4 Authoritative candidate.
// This source is intentionally separate from the live v4 function. PPLNS/multi-output
// activation remains null until the combined deployment gate is ratified.
const U=Deno.env.get('SUPABASE_URL'),S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),N='fairyelf-public-testnet-v4';
const C=100000000n,I=10n*C,ERA=600000,MAX=12000000n*C,START=18,RI=20,TARGET=180,MIN=12,MAXB=28,MAX_TXS=20,MAX_COINBASE_OUTPUTS=256;
const PPLNS_COINBASE_ACTIVATION_HEIGHT=null;
const HRP='faet',CS='qpzry9x8gf2tvdw0s3jn54khce6mua7l',BM=0x2bc830a3,E=new TextEncoder();
const H={'access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
function canon(v){if(Array.isArray(v))return v.map(canon);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])]));return v}
function stable(v){return JSON.stringify(canon(v))}
function hex(b){return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sha(b){return new Uint8Array(await crypto.subtle.digest('SHA-256',b))}
async function dh(v){const a=await sha(E.encode(stable(v)));return hex(await sha(a))}
function lz(h){let n=0;for(const c of h){const v=parseInt(c,16);if(v===0){n+=4;continue}if(v<2)n+=3;else if(v<4)n+=2;else if(v<8)n++;break}return n}
function pm(a){const G=[0x3b6a57b2,0x26508e6d,0x1ea119fa,0x3d4233dd,0x2a1462b3];let c=1;for(const x of a){const t=c>>>25;c=((c&0x1ffffff)<<5)^x;for(let i=0;i<5;i++)if((t>>>i)&1)c^=G[i]}return c>>>0}
function he(h){return[...h].map(c=>c.charCodeAt(0)>>>5).concat([0],[...h].map(c=>c.charCodeAt(0)&31))}
function cv(d,f,t,p=true){let a=0,b=0,r=[],m=(1<<t)-1,ma=(1<<(f+t-1))-1;for(const v of d){if(v<0||(v>>>f)!==0)throw Error('bit conversion');a=((a<<f)|v)&ma;b+=f;while(b>=t){b-=t;r.push((a>>>b)&m)}}if(p){if(b)r.push((a<<(t-b))&m)}else if(b>=f||((a<<(t-b))&m))throw Error('padding');return r}
function checksum(d){const m=(pm([...he(HRP),...d,0,0,0,0,0,0])^BM)>>>0;return Array.from({length:6},(_,i)=>(m>>>(5*(5-i)))&31)}
function encAddr(p){const d=cv(p,8,5,true);return HRP+'1'+[...d,...checksum(d)].map(v=>CS[v]).join('')}
function validAddr(a){try{if(typeof a!=='string'||a.length<8||a.length>90||a!==a.toLowerCase())return false;const s=a.lastIndexOf('1');if(a.slice(0,s)!==HRP)return false;const v=[...a.slice(s+1)].map(c=>CS.indexOf(c));if(v.some(x=>x<0)||pm([...he(HRP),...v])!==BM)return false;return cv(v.slice(0,-6),5,8,false).length===20}catch{return false}}
function b64d(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function atom(v,f='amount'){if(typeof v==='bigint')return v;if(typeof v==='number'&&Number.isSafeInteger(v)&&v>=0)return BigInt(v);if(typeof v==='string'&&/^\d+$/.test(v))return BigInt(v);throw Error('invalid '+f+' integer')}
function sub(h){const e=Math.floor((h-1)/ERA);return e>=63?0n:I>>BigInt(e)}
function fmt(a){const w=a/C,f=(a%C).toString().padStart(8,'0').replace(/0+$/,'');return f?`${w}.${f}`:w.toString()}
function activationConfigured(){return Number.isSafeInteger(PPLNS_COINBASE_ACTIVATION_HEIGHT)&&PPLNS_COINBASE_ACTIVATION_HEIGHT>=1}
function coinbaseActive(h){return activationConfigured()&&Number(h)>=PPLNS_COINBASE_ACTIVATION_HEIGHT}
async function rest(p,o={}){const r=await fetch(U+'/rest/v1/'+p,{...o,headers:{apikey:S,authorization:'Bearer '+S,'content-type':'application/json',...(o.headers||{})}}),t=await r.text();if(!r.ok)throw Error('db '+r.status+' '+t);return t?JSON.parse(t):null}
async function recent(n=20){return await rest(`fae_v4_blocks?select=height,hash,previous_hash,timestamp_ms,difficulty_bits,nonce,miner_address,reward_atoms,fee_atoms,coinbase_outputs,coinbase_mode,txids&order=height.desc&limit=${n}`)}
function bits(rows){if(!rows.length)return START;let b=Number(rows[0].difficulty_bits),next=Number(rows[0].height)+1;if(next%RI!==1||rows.length<RI)return b;const s=rows.slice(0,RI).reverse(),actual=Math.max(1,(Number(s.at(-1).timestamp_ms)-Number(s[0].timestamp_ms))/1000),expected=TARGET*(RI-1);let d=Math.round(Math.log2(expected/actual));d=Math.max(-2,Math.min(2,d));return Math.max(MIN,Math.min(MAXB,b+d))}
async function issued(){let a=0n;for(const r of await rest('fae_v4_blocks?select=reward_atoms'))a+=atom(r.reward_atoms);return a}
async function pending(){const rows=await rest(`fae_v4_transactions?select=txid,mempool_seq,fee_atoms,status&status=eq.pending&order=mempool_seq.asc&limit=${MAX_TXS}`);return rows.map(row=>({txid:String(row.txid),fee_atoms:String(row.fee_atoms??0),mempool_seq:Number(row.mempool_seq)}))}
async function recordsForTxids(txids){if(!txids.length)return[];if(txids.some(id=>!/^[0-9a-f]{64}$/.test(id)))throw Error('invalid txid');const filter=txids.join(',');const rows=await rest(`fae_v4_transactions?select=txid,fee_atoms,status&txid=in.(${filter})`);const map=new Map(rows.map(row=>[String(row.txid),row]));return txids.map(id=>{const row=map.get(id);if(!row||row.status!=='pending')throw Error('tx_not_pending:'+id);return{txid:id,fee_atoms:String(row.fee_atoms??0)}})}
function sumFees(records){return records.reduce((sum,row)=>sum+atom(row.fee_atoms,'fee'),0n)}
function normalizeWeights(weights){if(!Array.isArray(weights)||weights.length<1||weights.length>MAX_COINBASE_OUTPUTS)throw Error('invalid payout weights');const aggregated=new Map();for(const row of weights){const address=String(row?.address||''),weight=atom(row?.weight,'weight');if(!validAddr(address)||weight<=0n)throw Error('invalid payout weight');aggregated.set(address,(aggregated.get(address)||0n)+weight)}return[...aggregated.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([address,weight])=>({address,weight}))}
function allocate(total,weights){const totalWeight=weights.reduce((s,row)=>s+row.weight,0n);let allocated=0n;return weights.map((row,index)=>{const amount=index===weights.length-1?total-allocated:(total*row.weight)/totalWeight;allocated+=amount;return{address:row.address,amount_atoms:amount.toString()}}).filter(row=>BigInt(row.amount_atoms)>0n)}
async function status(){const r=await recent(),t=r[0]||null,i=await issued();return{ok:true,node_version:'authoritative-candidate-v1',network:N,height:t?Number(t.height):0,tip_hash:t?.hash||'0'.repeat(64),difficulty_bits:bits(r),target_seconds:TARGET,issued_atoms:i.toString(),issued_fae:fmt(i),max_supply_fae:'12000000',initial_subsidy_fae:'10',halving_era_blocks:ERA,template_policy:'snapshot',pplns_coinbase_activation_height:PPLNS_COINBASE_ACTIVATION_HEIGHT,coinbase_policy:activationConfigured()?'activation-configured':'candidate-inactive'}}
async function state(){const s=await status(),r=await recent(12);return{...s,recent:r.map(x=>({...x,height:Number(x.height),timestamp_ms:Number(x.timestamp_ms),difficulty_bits:Number(x.difficulty_bits),nonce:Number(x.nonce),reward_atoms:String(x.reward_atoms),fee_atoms:String(x.fee_atoms??0),txids:Array.isArray(x.txids)?x.txids:[],coinbase_outputs:Array.isArray(x.coinbase_outputs)?x.coinbase_outputs:null,coinbase_mode:x.coinbase_mode??null}))}}
async function baseTemplate(address){if(!validAddr(address))throw Error('invalid faet1 address');const r=await recent(),t=r[0]||null,h=t?Number(t.height)+1:1,b=bits(r),is=await issued();if(is>=MAX)throw Error('supply cap reached');const reward=sub(h)<MAX-is?sub(h):MAX-is,records=await pending(),txids=records.map(row=>row.txid),fees=sumFees(records),header={network:N,height:h,previous_hash:t?.hash||'0'.repeat(64),timestamp_ms:Date.now(),difficulty_bits:b,miner_address:address,reward_atoms:reward.toString(),tx_root:await dh(txids),tx_count:txids.length};return{header,txids,reward,fees}}
async function template(address){try{const base=await baseTemplate(address);if(!coinbaseActive(base.header.height))return J({ok:true,template_policy:'snapshot',header:base.header,txids:base.txids});const coinbase_outputs=[{address,amount_atoms:(base.reward+base.fees).toString()}],header={...base.header,fee_atoms:base.fees.toString(),coinbase_root:await dh(coinbase_outputs),coinbase_count:1,coinbase_mode:'direct'};return J({ok:true,template_policy:'snapshot',header,txids:base.txids,coinbase_outputs,payouts:coinbase_outputs})}catch(e){return J({ok:false,error:String(e?.message||e)},String(e?.message||e).includes('supply cap')?409:400)}}
async function pplnsTemplate(body){try{const weights=normalizeWeights(body?.weights),base=await baseTemplate(weights[0].address);if(!coinbaseActive(base.header.height))return J({ok:false,error:'pplns_coinbase_activation_required'},409);const coinbase_outputs=allocate(base.reward+base.fees,weights);if(!coinbase_outputs.length)throw Error('empty payout allocation');const header={...base.header,miner_address:coinbase_outputs[0].address,fee_atoms:base.fees.toString(),coinbase_root:await dh(coinbase_outputs),coinbase_count:coinbase_outputs.length,coinbase_mode:'pplns-direct'};return J({ok:true,template_policy:'snapshot',header,txids:base.txids,coinbase_outputs,payouts:coinbase_outputs})}catch(e){return J({ok:false,error:String(e?.message||e)},400)}}
async function balance(a){if(!validAddr(a))return J({ok:false,error:'invalid address'},400);const r=await rest(`fae_v4_utxos?select=outpoint,amount_atoms,created_height&address=eq.${encodeURIComponent(a)}&spent=eq.false&order=created_height.asc`);let z=0n;for(const x of r)z+=atom(x.amount_atoms);return J({ok:true,address:a,balance_atoms:z.toString(),balance_fae:fmt(z),utxo_count:r.length,utxos:r.map(x=>({...x,amount_atoms:String(x.amount_atoms)}))})}
async function spendable(a){if(!validAddr(a))return J({ok:false,error:'invalid address'},400);const c=await rest(`fae_v4_utxos?select=outpoint,amount_atoms,created_height&address=eq.${encodeURIComponent(a)}&spent=eq.false&order=created_height.asc`),p=await rest(`fae_v4_mempool_outputs?select=outpoint,amount_atoms,txid,output_index,created_at&address=eq.${encodeURIComponent(a)}&order=created_at.asc`),sp=await rest('fae_v4_mempool_spends?select=outpoint'),rs=new Set(sp.map(x=>String(x.outpoint))),u=[];let z=0n;for(const x of c)if(!rs.has(String(x.outpoint))){const m=atom(x.amount_atoms);z+=m;u.push({outpoint:String(x.outpoint),amount_atoms:m.toString(),source:'confirmed',created_height:Number(x.created_height)})}for(const x of p)if(!rs.has(String(x.outpoint))){const m=atom(x.amount_atoms);z+=m;u.push({outpoint:String(x.outpoint),amount_atoms:m.toString(),source:'pending',parent_txid:String(x.txid)})}return J({ok:true,address:a,spendable_atoms:z.toString(),spendable_fae:fmt(z),utxos:u})}
function txPayload(t){return{domain:'FAIRYELF_TX_V2',network:t.network,inputs:t.inputs,outputs:t.outputs,public_key_spki:t.public_key_spki}}
async function verifyTx(t){if(!t||t.version!==2||t.network!==N||!Array.isArray(t.inputs)||!t.inputs.length||t.inputs.length>64||!Array.isArray(t.outputs)||!t.outputs.length||t.outputs.length>16)return{ok:false,error:'malformed transaction'};if(typeof t.public_key_spki!=='string'||typeof t.signature!=='string')return{ok:false,error:'missing signature'};if(t.inputs.some(x=>typeof x!=='string'||x.length>160)||new Set(t.inputs).size!==t.inputs.length)return{ok:false,error:'invalid inputs'};for(const o of t.outputs){if(!validAddr(o?.address))return{ok:false,error:'invalid output address'};try{if(atom(o.amount_atoms)<=0n)return{ok:false,error:'invalid output amount'}}catch{return{ok:false,error:'invalid output amount'}}}try{const sp=b64d(t.public_key_spki),pk=await crypto.subtle.importKey('spki',sp,{name:'Ed25519'},true,['verify']),from=encAddr((await sha(sp)).slice(0,20)),ok=await crypto.subtle.verify({name:'Ed25519'},pk,b64d(t.signature),E.encode(stable(txPayload(t))));if(!ok)return{ok:false,error:'invalid signature'};return{ok:true,from,txid:await dh(t)}}catch{return{ok:false,error:'invalid public key/signature'}}}
async function submitTx(body){const t=body?.tx||body,v=await verifyTx(t);if(!v.ok)return J(v,400);const r=await rest('rpc/fae_v4_accept_tx',{method:'POST',body:JSON.stringify({p_txid:v.txid,p_network:t.network,p_from_address:v.from,p_public_key_spki:t.public_key_spki,p_signature:t.signature,p_inputs:t.inputs,p_outputs:t.outputs})});return J(r,r?.ok?200:409)}
async function history(a){if(!validAddr(a))return J({ok:false,error:'invalid address'},400);const r=await rest('fae_v4_transactions?select=txid,from_address,inputs,outputs,fee_atoms,status,confirmed_height,created_at,mempool_seq&order=mempool_seq.desc&limit=100');return J({ok:true,transactions:r.filter(x=>x.from_address===a||(Array.isArray(x.outputs)&&x.outputs.some(o=>o.address===a))).slice(0,30).map(x=>({...x,fee_atoms:String(x.fee_atoms??0)}))})}
async function validateActiveCoinbase(h,txids,body,reward){const outputs=body?.coinbase_outputs;if(!Array.isArray(outputs)||outputs.length<1||outputs.length>MAX_COINBASE_OUTPUTS)throw Error('invalid_coinbase_output_count');const normalized=[];let total=0n;for(const [index,o] of outputs.entries()){const address=String(o?.address||''),amount_atoms=String(o?.amount_atoms??'');if(!validAddr(address)||!/^\d+$/.test(amount_atoms)||BigInt(amount_atoms)<=0n)throw Error('invalid_coinbase_output:'+index);normalized.push({address,amount_atoms});total+=BigInt(amount_atoms)}const records=await recordsForTxids(txids),fees=sumFees(records);if(String(h.fee_atoms)!==fees.toString())throw Error('fee_commitment_mismatch');if(Number(h.coinbase_count)!==normalized.length)throw Error('coinbase_count_mismatch');if(h.coinbase_root!==await dh(normalized))throw Error('coinbase_commitment_mismatch');if(h.coinbase_mode!=='direct'&&h.coinbase_mode!=='pplns-direct')throw Error('invalid_coinbase_mode');if(h.miner_address!==normalized[0].address)throw Error('primary_coinbase_address_mismatch');if(h.coinbase_mode==='direct'&&normalized.length!==1)throw Error('direct_coinbase_requires_one_output');if(total!==reward+fees)throw Error('invalid_coinbase_value');return{outputs:normalized,fees}}
async function submitBlock(body){const h=body?.header,n=Number(body?.nonce),hash=String(body?.hash||''),txids=Array.isArray(body?.txids)?body.txids.map(String):[];if(!h||h.network!==N||!Number.isSafeInteger(n)||n<0||!/^[0-9a-f]{64}$/.test(hash)||!validAddr(h.miner_address))return J({ok:false,error:'malformed submission'},400);if(txids.length>MAX_TXS||new Set(txids).size!==txids.length||txids.some(id=>!/^[0-9a-f]{64}$/.test(id)))return J({ok:false,error:'invalid tx list'},400);if(h.tx_root!==await dh(txids)||Number(h.tx_count)!==txids.length)return J({ok:false,error:'tx commitment mismatch'},400);
  const r=await recent(),t=r[0]||null,eh=t?Number(t.height)+1:1,ep=t?.hash||'0'.repeat(64),b=bits(r),is=await issued(),reward=sub(eh)<MAX-is?sub(eh):MAX-is;if(h.height!==eh||h.previous_hash!==ep)return J({ok:false,error:'stale_tip',height:eh-1,tip_hash:ep},409);if(h.difficulty_bits!==b||String(h.reward_atoms)!==reward.toString())return J({ok:false,error:'invalid consensus fields'},400);
  const now=Date.now();if(!Number.isSafeInteger(h.timestamp_ms)||h.timestamp_ms>now+120000||(t&&h.timestamp_ms<Number(t.timestamp_ms)))return J({ok:false,error:'invalid timestamp'},400);
  let active=null;if(coinbaseActive(eh)){try{active=await validateActiveCoinbase(h,txids,body,reward)}catch(e){return J({ok:false,error:String(e?.message||e)},400)}}else if(h.fee_atoms!==undefined||h.coinbase_root!==undefined||h.coinbase_count!==undefined||h.coinbase_mode!==undefined||body?.coinbase_outputs!=null){return J({ok:false,error:'premature_coinbase_v1_fields'},400)}
  const computed=await dh({...h,nonce:n});if(computed!==hash||lz(hash)<b)return J({ok:false,error:'invalid proof of work'},400);
  if(!active){const q=await rest('rpc/fae_v4_accept_block_v2',{method:'POST',body:JSON.stringify({p_height:h.height,p_hash:hash,p_previous_hash:h.previous_hash,p_timestamp_ms:h.timestamp_ms,p_difficulty_bits:h.difficulty_bits,p_nonce:n,p_miner_address:h.miner_address,p_reward_atoms:String(h.reward_atoms),p_header_json:{...h,nonce:n},p_txids:txids})});return J(q,q?.ok?200:409)}
  const q=await rest('rpc/fae_v4_accept_block_v3',{method:'POST',body:JSON.stringify({p_height:h.height,p_hash:hash,p_previous_hash:h.previous_hash,p_timestamp_ms:h.timestamp_ms,p_difficulty_bits:h.difficulty_bits,p_nonce:n,p_miner_address:h.miner_address,p_reward_atoms:String(h.reward_atoms),p_fee_atoms:active.fees.toString(),p_coinbase_outputs:active.outputs,p_coinbase_mode:h.coinbase_mode,p_header_json:{...h,nonce:n},p_txids:txids})});return J(q,q?.ok?200:409)}

Deno.serve(async req=>{try{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:H});const u=new URL(req.url);if(u.pathname.endsWith('/status'))return J(await status());if(u.pathname.endsWith('/state'))return J(await state());if(u.pathname.endsWith('/template')&&req.method==='GET')return await template(u.searchParams.get('address')||'');if(u.pathname.endsWith('/template/pplns')&&req.method==='POST')return await pplnsTemplate(await req.json());if(u.pathname.endsWith('/balance'))return await balance(u.searchParams.get('address')||'');if(u.pathname.endsWith('/spendable'))return await spendable(u.searchParams.get('address')||'');if(u.pathname.endsWith('/submit-tx')&&req.method==='POST')return await submitTx(await req.json());if(u.pathname.endsWith('/transactions'))return await history(u.searchParams.get('address')||'');if(u.pathname.endsWith('/submit-block')&&req.method==='POST')return await submitBlock(await req.json());return J({name:'FAE public testnet v4 Authoritative candidate',network:N,activation_height:PPLNS_COINBASE_ACTIVATION_HEIGHT,endpoints:['/status','/state','/template','/template/pplns','/balance','/spendable','/submit-tx','/transactions','/submit-block']})}catch(e){console.error(e);return J({ok:false,error:String(e?.message||e)},500)}});
