#!/usr/bin/env node
'use strict';

import http from 'node:http';
import { createHash, createPublicKey, verify as verifySignature } from 'node:crypto';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const NETWORK='fairyelf-public-testnet-v4';
const COIN=100000000n;
const INITIAL_SUBSIDY=10n*COIN;
const HALVING_ERA_BLOCKS=600000;
const MAX_SUPPLY=12000000n*COIN;
const START_BITS=18;
const RETARGET_INTERVAL=20;
const TARGET_SECONDS=180;
const MIN_BITS=12;
const MAX_BITS=28;
const MAX_TXS_PER_BLOCK=20;
const MAX_INPUTS=64;
const MAX_OUTPUTS=16;
const NODE_VERSION='independent-0.1.0';
const HRP='faet';
const CHARSET='qpzry9x8gf2tvdw0s3jn54khce6mua7l';
const BECH32M_CONST=0x2bc830a3;
const ZERO_HASH='0'.repeat(64);
const DEFAULT_PUBLIC_API='https://wfwwotuhectwknvbvgif.supabase.co/functions/v1/fae-public-testnet-v4';
const DEFAULT_CHAIN_FEED='https://wfwwotuhectwknvbvgif.supabase.co/functions/v1/fae-chain-feed-v1';

const PORT=Number(process.env.FAE_PORT||8787);
const HOST=process.env.FAE_HOST||'0.0.0.0';
const DATA_FILE=resolve(process.env.FAE_DATA_FILE||'./data/fae-state.json');
const SYNC_MS=Math.max(5000,Number(process.env.FAE_SYNC_MS||15000));
const UPSTREAM_API=(process.env.FAE_UPSTREAM_API===undefined?DEFAULT_PUBLIC_API:process.env.FAE_UPSTREAM_API).trim().replace(/\/$/,'');
const PEERS=parseList(process.env.FAE_PEERS||'');
const FEEDS=parseList(process.env.FAE_BOOTSTRAP_FEEDS===undefined?DEFAULT_CHAIN_FEED:process.env.FAE_BOOTSTRAP_FEEDS);
const ENABLE_SYNC=process.env.FAE_SYNC!=='0';

function parseList(value){return String(value||'').split(',').map(x=>x.trim().replace(/\/$/,'')).filter(Boolean)}
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])]));return value}
function stable(value){return JSON.stringify(canonical(value))}
function sha256(bytes){return createHash('sha256').update(bytes).digest()}
function doubleHash(value){const first=sha256(Buffer.from(stable(value)));return sha256(first).toString('hex')}
function leadingZeroBits(hash){let count=0;for(const character of hash){const value=parseInt(character,16);if(value===0){count+=4;continue}if(value<2)count+=3;else if(value<4)count+=2;else if(value<8)count++;break}return count}
function atom(value,field='amount'){if(typeof value==='bigint')return value;if(typeof value==='number'&&Number.isSafeInteger(value)&&value>=0)return BigInt(value);if(typeof value==='string'&&/^\d+$/.test(value))return BigInt(value);throw Error('invalid '+field+' integer')}
function subsidy(height){const era=Math.floor((height-1)/HALVING_ERA_BLOCKS);return era>=63?0n:INITIAL_SUBSIDY>>BigInt(era)}
function formatAtoms(amount){const a=BigInt(amount);const whole=a/COIN;const fraction=(a%COIN).toString().padStart(8,'0').replace(/0+$/,'');return fraction?`${whole}.${fraction}`:whole.toString()}
function chainWork(chain){return chain.reduce((sum,b)=>sum+(1n<<BigInt(Number(b.difficulty_bits))),0n)}
function tip(state){return state.chain.at(-1)||null}
function issued(state){return state.chain.reduce((sum,b)=>sum+BigInt(b.reward_atoms),0n)}
function nextDifficulty(chain){if(!chain.length)return START_BITS;const last=chain.at(-1);let bits=Number(last.difficulty_bits),next=Number(last.height)+1;if(next%RETARGET_INTERVAL!==1||chain.length<RETARGET_INTERVAL)return bits;const rows=chain.slice(-RETARGET_INTERVAL);const actual=Math.max(1,(Number(rows.at(-1).timestamp_ms)-Number(rows[0].timestamp_ms))/1000);const expected=TARGET_SECONDS*(RETARGET_INTERVAL-1);let delta=Math.round(Math.log2(expected/actual));delta=Math.max(-2,Math.min(2,delta));return Math.max(MIN_BITS,Math.min(MAX_BITS,bits+delta))}

function polymod(values){const generators=[0x3b6a57b2,0x26508e6d,0x1ea119fa,0x3d4233dd,0x2a1462b3];let checksum=1;for(const value of values){const top=checksum>>>25;checksum=((checksum&0x1ffffff)<<5)^value;for(let i=0;i<5;i++)if((top>>>i)&1)checksum^=generators[i]}return checksum>>>0}
function hrpExpand(hrp){return [...hrp].map(c=>c.charCodeAt(0)>>>5).concat([0],[...hrp].map(c=>c.charCodeAt(0)&31))}
function convertBits(data,fromBits,toBits,pad=true){let accumulator=0,bitCount=0;const result=[],mask=(1<<toBits)-1,maxAccumulator=(1<<(fromBits+toBits-1))-1;for(const value of data){if(value<0||(value>>>fromBits)!==0)throw Error('bit conversion');accumulator=((accumulator<<fromBits)|value)&maxAccumulator;bitCount+=fromBits;while(bitCount>=toBits){bitCount-=toBits;result.push((accumulator>>>bitCount)&mask)}}if(pad){if(bitCount)result.push((accumulator<<(toBits-bitCount))&mask)}else if(bitCount>=fromBits||((accumulator<<(toBits-bitCount))&mask))throw Error('padding');return result}
function encodeAddress(payload){const data=convertBits(payload,8,5,true);const mod=(polymod([...hrpExpand(HRP),...data,0,0,0,0,0,0])^BECH32M_CONST)>>>0;const checksum=Array.from({length:6},(_,i)=>(mod>>>(5*(5-i)))&31);return HRP+'1'+[...data,...checksum].map(v=>CHARSET[v]).join('')}
function validAddress(address){try{if(typeof address!=='string'||address.length<8||address.length>90||address!==address.toLowerCase())return false;const separator=address.lastIndexOf('1');if(address.slice(0,separator)!==HRP)return false;const values=[...address.slice(separator+1)].map(c=>CHARSET.indexOf(c));if(values.some(v=>v<0)||polymod([...hrpExpand(HRP),...values])!==BECH32M_CONST)return false;return convertBits(values.slice(0,-6),5,8,false).length===20}catch{return false}}

function txPayload(tx){return{domain:'FAIRYELF_TX_V2',network:tx.network,inputs:tx.inputs,outputs:tx.outputs,public_key_spki:tx.public_key_spki}}
function normalizeTx(tx){return{version:2,network:String(tx.network),inputs:[...(tx.inputs||[])].map(String),outputs:[...(tx.outputs||[])].map(o=>({address:String(o.address),amount_atoms:String(o.amount_atoms)})),public_key_spki:String(tx.public_key_spki),signature:String(tx.signature)}}
function deriveFromAddress(spki){return encodeAddress(sha256(spki).subarray(0,20))}
function verifyTxCrypto(raw){try{const tx=normalizeTx(raw);if(raw?.version!==undefined&&Number(raw.version)!==2)return{ok:false,error:'wrong_version'};if(tx.network!==NETWORK||tx.inputs.length<1||tx.inputs.length>MAX_INPUTS||tx.outputs.length<1||tx.outputs.length>MAX_OUTPUTS)return{ok:false,error:'malformed_transaction'};if(new Set(tx.inputs).size!==tx.inputs.length||tx.inputs.some(x=>!x||x.length>160))return{ok:false,error:'invalid_inputs'};for(const output of tx.outputs){if(!validAddress(output.address)||atom(output.amount_atoms)<=0n)return{ok:false,error:'invalid_output'}}const spki=Buffer.from(tx.public_key_spki,'base64'),signature=Buffer.from(tx.signature,'base64');const key=createPublicKey({key:spki,format:'der',type:'spki'});if(!verifySignature(null,Buffer.from(stable(txPayload(tx))),key,signature))return{ok:false,error:'invalid_signature'};const from=deriveFromAddress(spki);const full={...tx};const txid=doubleHash(full);return{ok:true,tx,from,txid}}catch(error){return{ok:false,error:'invalid_public_key_or_signature',detail:error.message}}}

function emptyState(){return{format:'FAE_NODE_STATE_V1',network:NETWORK,chain:[],transactions:{},mempoolOrder:[],mempoolSeq:0,utxos:{},mempoolSpends:{},mempoolOutputs:{}}}
let state=emptyState();
let writeLock=Promise.resolve();
let syncRunning=false;

async function loadState(){try{const raw=JSON.parse(await readFile(DATA_FILE,'utf8'));if(raw?.network!==NETWORK||!Array.isArray(raw.chain))throw Error('wrong state format/network');state={...emptyState(),...raw};console.log(`[FAE] loaded height ${state.chain.length} from ${DATA_FILE}`)}catch(error){if(error.code!=='ENOENT')console.warn('[FAE] state load failed, starting empty:',error.message)}}
async function persist(){await mkdir(dirname(DATA_FILE),{recursive:true});const tmp=DATA_FILE+'.tmp';await writeFile(tmp,JSON.stringify(state,null,2));await rename(tmp,DATA_FILE)}
function serial(operation){const run=writeLock.then(operation,operation);writeLock=run.catch(()=>{});return run}
function cloneState(source=state){return structuredClone(source)}

function spendableOutputs(s,address){const rows=[];for(const [outpoint,u] of Object.entries(s.utxos))if(!u.spent&&u.address===address&&!s.mempoolSpends[outpoint])rows.push({outpoint,amount_atoms:String(u.amount_atoms),source:'confirmed',created_height:u.created_height});for(const [outpoint,u] of Object.entries(s.mempoolOutputs))if(u.address===address&&!s.mempoolSpends[outpoint])rows.push({outpoint,amount_atoms:String(u.amount_atoms),source:'pending',parent_txid:u.txid});return rows}
function balanceAtoms(s,address){let total=0n;for(const u of Object.values(s.utxos))if(!u.spent&&u.address===address)total+=BigInt(u.amount_atoms);return total}

function acceptTxInto(s,raw,{fromFeed=false}= {}){const verified=verifyTxCrypto(raw);if(!verified.ok)throw Object.assign(Error(verified.error),{code:verified.error});const {tx,from,txid}=verified;if(raw.txid&&raw.txid!==txid)throw Object.assign(Error('txid_mismatch'),{code:'txid_mismatch'});if(raw.from_address&&raw.from_address!==from)throw Object.assign(Error('from_key_mismatch'),{code:'from_key_mismatch'});if(s.transactions[txid])throw Object.assign(Error('duplicate_txid'),{code:'duplicate_txid'});let inputSum=0n;for(const outpoint of tx.inputs){let output=s.utxos[outpoint];if(output?.spent)output=null;if(!output)output=s.mempoolOutputs[outpoint];if(!output)throw Object.assign(Error('missing_or_spent_input'),{code:'missing_or_spent_input',outpoint});if(output.address!==from)throw Object.assign(Error('input_not_owned'),{code:'input_not_owned',outpoint});if(s.mempoolSpends[outpoint])throw Object.assign(Error('input_reserved'),{code:'input_reserved',outpoint});inputSum+=BigInt(output.amount_atoms)}let outputSum=0n;for(const output of tx.outputs)outputSum+=BigInt(output.amount_atoms);if(outputSum>inputSum)throw Object.assign(Error('overspend'),{code:'overspend'});const fee=(inputSum-outputSum).toString();const seq=fromFeed?Number(raw.mempool_seq||++s.mempoolSeq):++s.mempoolSeq;s.mempoolSeq=Math.max(s.mempoolSeq,seq);s.transactions[txid]={txid,network:NETWORK,from_address:from,public_key_spki:tx.public_key_spki,signature:tx.signature,inputs:tx.inputs,outputs:tx.outputs,fee_atoms:fee,status:'pending',confirmed_height:null,mempool_seq:seq,created_at:raw.created_at||new Date().toISOString()};s.mempoolOrder.push(txid);for(const outpoint of tx.inputs)s.mempoolSpends[outpoint]=txid;tx.outputs.forEach((output,index)=>{s.mempoolOutputs[`${txid}:${index}`]={outpoint:`${txid}:${index}`,txid,output_index:index,address:output.address,amount_atoms:String(output.amount_atoms)}});return s.transactions[txid]}

function applyConfirmedTx(s,record,height){const txid=record.txid;const existing=s.transactions[txid];const tx=normalizeTx(record);const verified=verifyTxCrypto(tx);if(!verified.ok||verified.txid!==txid)throw Error(`invalid_tx:${txid}:${verified.error||'txid'}`);if(record.from_address&&record.from_address!==verified.from)throw Error(`from_key_mismatch:${txid}`);let inputSum=0n;for(const outpoint of tx.inputs){const output=s.utxos[outpoint];if(!output||output.spent)throw Error(`bad_input:${txid}:${outpoint}`);if(output.address!==verified.from)throw Error(`input_owner:${txid}:${outpoint}`);inputSum+=BigInt(output.amount_atoms);output.spent=true;output.spent_by=txid}let outputSum=0n;tx.outputs.forEach((output,index)=>{const amount=BigInt(output.amount_atoms);outputSum+=amount;s.utxos[`${txid}:${index}`]={outpoint:`${txid}:${index}`,address:output.address,amount_atoms:amount.toString(),created_height:height,spent:false,spent_by:null}});const fee=BigInt(record.fee_atoms??(inputSum-outputSum));if(inputSum!==outputSum+fee)throw Error(`conservation:${txid}`);s.transactions[txid]={txid,network:NETWORK,from_address:verified.from,public_key_spki:tx.public_key_spki,signature:tx.signature,inputs:tx.inputs,outputs:tx.outputs,fee_atoms:fee.toString(),status:'confirmed',confirmed_height:height,mempool_seq:Number(record.mempool_seq||existing?.mempool_seq||0),created_at:record.created_at||existing?.created_at||new Date().toISOString()};delete s.mempoolSpends[txid];for(const outpoint of tx.inputs)delete s.mempoolSpends[outpoint];tx.outputs.forEach((_,index)=>delete s.mempoolOutputs[`${txid}:${index}`]);s.mempoolOrder=s.mempoolOrder.filter(id=>id!==txid)}

function expectedReward(s,height){const remaining=MAX_SUPPLY-issued(s);if(remaining<=0n)return 0n;const sub=subsidy(height);return sub<remaining?sub:remaining}
function validateBlockEnvelope(s,header,nonce,hash,txids,{allowFutureClock=true}={}){const previous=tip(s);const height=previous?Number(previous.height)+1:1;if(!header||header.network!==NETWORK||!Number.isSafeInteger(nonce)||nonce<0||!/^[0-9a-f]{64}$/.test(hash)||!validAddress(header.miner_address))throw Error('malformed_submission');if(!Array.isArray(txids)||txids.length>MAX_TXS_PER_BLOCK||new Set(txids).size!==txids.length)throw Error('invalid_tx_list');if(Number(header.height)!==height||header.previous_hash!==(previous?.hash||ZERO_HASH))throw Error('stale_tip');const bits=nextDifficulty(s.chain);if(Number(header.difficulty_bits)!==bits||String(header.reward_atoms)!==expectedReward(s,height).toString())throw Error('invalid_consensus_fields');if(doubleHash(txids)!==header.tx_root||Number(header.tx_count)!==txids.length)throw Error('tx_commitment_mismatch');const now=Date.now();if(!Number.isSafeInteger(Number(header.timestamp_ms))||(allowFutureClock&&Number(header.timestamp_ms)>now+120000)||(previous&&Number(header.timestamp_ms)<Number(previous.timestamp_ms)))throw Error('invalid_timestamp');const computed=doubleHash({...header,nonce});if(computed!==hash||leadingZeroBits(hash)<bits)throw Error('invalid_proof_of_work');return{height,bits}}

function appendBlockFromSubmission(s,{header,nonce,hash,txids}){const {height}=validateBlockEnvelope(s,header,nonce,hash,txids);const temp=cloneState(s);for(const txid of txids){const record=temp.transactions[txid];if(!record||record.status!=='pending')throw Error('tx_not_pending:'+txid);applyConfirmedTx(temp,record,height)}temp.utxos[`${hash}:0`]={outpoint:`${hash}:0`,address:header.miner_address,amount_atoms:String(header.reward_atoms),created_height:height,spent:false,spent_by:null};temp.chain.push({height,hash,previous_hash:header.previous_hash,timestamp_ms:Number(header.timestamp_ms),difficulty_bits:Number(header.difficulty_bits),nonce:Number(nonce),miner_address:header.miner_address,reward_atoms:String(header.reward_atoms),header_json:{...header,nonce:Number(nonce)},txids:[...txids]});return temp}

function appendBlockFromFeed(s,block,txMap){const header=block.header_json;if(!header||Number(header.nonce)!==Number(block.nonce))throw Error(`missing_header:${block.height}`);const bare={...header};const nonce=Number(bare.nonce);delete bare.nonce;validateBlockEnvelope(s,bare,nonce,String(block.hash),(block.txids||[]).map(String),{allowFutureClock:false});if(Number(block.height)!==Number(bare.height)||String(block.previous_hash)!==String(bare.previous_hash)||Number(block.timestamp_ms)!==Number(bare.timestamp_ms)||Number(block.difficulty_bits)!==Number(bare.difficulty_bits)||String(block.miner_address)!==String(bare.miner_address)||String(block.reward_atoms)!==String(bare.reward_atoms))throw Error(`block_field_mismatch:${block.height}`);const temp=cloneState(s);for(const txid of block.txids||[]){const record=txMap.get(String(txid));if(!record)throw Error(`missing_tx:${txid}`);applyConfirmedTx(temp,{...record,txid:String(txid)},Number(block.height))}temp.utxos[`${block.hash}:0`]={outpoint:`${block.hash}:0`,address:block.miner_address,amount_atoms:String(block.reward_atoms),created_height:Number(block.height),spent:false,spent_by:null};temp.chain.push({height:Number(block.height),hash:String(block.hash),previous_hash:String(block.previous_hash),timestamp_ms:Number(block.timestamp_ms),difficulty_bits:Number(block.difficulty_bits),nonce:Number(block.nonce),miner_address:String(block.miner_address),reward_atoms:String(block.reward_atoms),header_json:header,txids:(block.txids||[]).map(String)});return temp}

function publicBlock(block){return{height:Number(block.height),hash:block.hash,previous_hash:block.previous_hash,timestamp_ms:Number(block.timestamp_ms),difficulty_bits:Number(block.difficulty_bits),nonce:Number(block.nonce),miner_address:block.miner_address,reward_atoms:String(block.reward_atoms),header_json:block.header_json,txids:[...(block.txids||[])]}}
function statusPayload(s=state){const last=tip(s),amount=issued(s);return{ok:true,node_version:NODE_VERSION,network:NETWORK,height:last?Number(last.height):0,tip_hash:last?.hash||ZERO_HASH,difficulty_bits:nextDifficulty(s.chain),target_seconds:TARGET_SECONDS,issued_atoms:amount.toString(),issued_fae:formatAtoms(amount),max_supply_fae:'12000000',initial_subsidy_fae:'10',halving_era_blocks:HALVING_ERA_BLOCKS,template_policy:'snapshot',chain_work:chainWork(s.chain).toString(),peer_count:PEERS.length+(UPSTREAM_API?1:0)}}

async function fetchJson(url,options={},timeout=12000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{...options,signal:controller.signal,headers:{'content-type':'application/json',...(options.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw Error(`${response.status}:${payload.error||payload.reason||response.statusText}`);return payload}finally{clearTimeout(timer)}}
async function relay(path,payload){const targets=[...(UPSTREAM_API?[UPSTREAM_API]:[]),...PEERS];await Promise.allSettled([...new Set(targets)].map(peer=>fetchJson(peer+path,{method:'POST',body:JSON.stringify(payload)},8000)))}
function feedUrl(base,from,limit){if(/fae-chain-feed-v1(?:\?|$)/.test(base))return `${base}${base.includes('?')?'&':'?'}from=${from}&limit=${limit}`;return `${base}/feed?from=${from}&limit=${limit}`}
async function fetchCandidate(base){let candidate=emptyState(),from=1,tipHeight=0;for(let page=0;page<100000;page++){const feed=await fetchJson(feedUrl(base,from,250),{},15000);if(feed.network!==NETWORK)throw Error('peer_wrong_network');tipHeight=Number(feed.tip_height||0);const blocks=Array.isArray(feed.blocks)?feed.blocks:[];const txMap=new Map((feed.transactions||[]).map(tx=>[String(tx.txid),tx]));if(!blocks.length){if(from<=tipHeight)throw Error('peer_feed_gap');break}for(const block of blocks){if(Number(block.height)!==candidate.chain.length+1)throw Error('peer_height_gap');candidate=appendBlockFromFeed(candidate,block,txMap)}from=candidate.chain.length+1;if(candidate.chain.length>=tipHeight)break}return candidate}
function preferred(candidate,current){const cw=chainWork(candidate.chain),ow=chainWork(current.chain);if(cw!==ow)return cw>ow;const ct=tip(candidate)?.hash||ZERO_HASH,ot=tip(current)?.hash||ZERO_HASH;return candidate.chain.length>0&&cw===ow&&ct<ot}
async function syncOnce(){if(syncRunning)return;syncRunning=true;try{for(const source of [...new Set([...FEEDS,...PEERS])]){try{const candidate=await fetchCandidate(source);if(preferred(candidate,state)){await serial(async()=>{if(preferred(candidate,state)){state=candidate;await persist();console.log(`[FAE] adopted verified chain height ${state.chain.length} from ${source}`)}})}}catch(error){console.warn(`[FAE] sync source ${source}: ${error.message}`)}}}finally{syncRunning=false}}

function cors(){return{'access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'no-store'}}
function send(res,status,payload){res.writeHead(status,cors());res.end(JSON.stringify(payload))}
async function readBody(req){let body='';for await(const chunk of req){body+=chunk;if(body.length>2_000_000)throw Error('body_too_large')}return body?JSON.parse(body):{}}

async function handler(req,res){try{if(req.method==='OPTIONS'){res.writeHead(204,cors());return res.end()}const url=new URL(req.url,'http://localhost');
  if(url.pathname==='/'||url.pathname==='/status')return send(res,200,statusPayload());
  if(url.pathname==='/state'){const recent=state.chain.slice(-12).reverse().map(publicBlock);return send(res,200,{...statusPayload(),recent})}
  if(url.pathname==='/feed'){const from=Math.max(1,Number(url.searchParams.get('from')||1)),limit=Math.max(1,Math.min(250,Number(url.searchParams.get('limit')||100))),to=from+limit-1;const blocks=state.chain.filter(b=>b.height>=from&&b.height<=to).map(publicBlock);const heights=new Set(blocks.map(b=>b.height));const transactions=Object.values(state.transactions).filter(t=>t.status==='confirmed'&&heights.has(Number(t.confirmed_height))).sort((a,b)=>Number(a.confirmed_height)-Number(b.confirmed_height)||Number(a.mempool_seq)-Number(b.mempool_seq));const last=tip(state);return send(res,200,{ok:true,feed_version:1,network:NETWORK,from,limit,tip_height:last?.height||0,tip_hash:last?.hash||ZERO_HASH,blocks,transactions})}
  if(url.pathname==='/template'){const address=url.searchParams.get('address')||'';if(!validAddress(address))return send(res,400,{ok:false,error:'invalid faet1 address'});const last=tip(state),height=last?last.height+1:1,reward=expectedReward(state,height);if(reward<=0n)return send(res,409,{ok:false,error:'supply cap reached'});const txids=state.mempoolOrder.filter(id=>state.transactions[id]?.status==='pending').slice(0,MAX_TXS_PER_BLOCK);const header={network:NETWORK,height,previous_hash:last?.hash||ZERO_HASH,timestamp_ms:Date.now(),difficulty_bits:nextDifficulty(state.chain),miner_address:address,reward_atoms:reward.toString(),tx_root:doubleHash(txids),tx_count:txids.length};return send(res,200,{ok:true,template_policy:'snapshot',header,txids})}
  if(url.pathname==='/balance'){const address=url.searchParams.get('address')||'';if(!validAddress(address))return send(res,400,{ok:false,error:'invalid address'});const utxos=Object.entries(state.utxos).filter(([,u])=>u.address===address&&!u.spent).map(([outpoint,u])=>({outpoint,amount_atoms:String(u.amount_atoms),created_height:u.created_height}));const total=balanceAtoms(state,address);return send(res,200,{ok:true,address,balance_atoms:total.toString(),balance_fae:formatAtoms(total),utxo_count:utxos.length,utxos})}
  if(url.pathname==='/spendable'){const address=url.searchParams.get('address')||'';if(!validAddress(address))return send(res,400,{ok:false,error:'invalid address'});const utxos=spendableOutputs(state,address);const total=utxos.reduce((sum,u)=>sum+BigInt(u.amount_atoms),0n);return send(res,200,{ok:true,address,spendable_atoms:total.toString(),spendable_fae:formatAtoms(total),utxos})}
  if(url.pathname==='/transactions'){const address=url.searchParams.get('address')||'';if(!validAddress(address))return send(res,400,{ok:false,error:'invalid address'});const transactions=Object.values(state.transactions).filter(t=>t.from_address===address||t.outputs.some(o=>o.address===address)).sort((a,b)=>Number(b.mempool_seq)-Number(a.mempool_seq)).slice(0,30);return send(res,200,{ok:true,transactions})}
  if(url.pathname==='/submit-tx'&&req.method==='POST'){const body=await readBody(req);let accepted;try{await serial(async()=>{accepted=acceptTxInto(state,body?.tx||body);await persist()})}catch(error){return send(res,409,{ok:false,error:error.code||error.message})}relay('/submit-tx',{tx:normalizeTx(body?.tx||body)}).catch(()=>{});return send(res,200,{ok:true,txid:accepted.txid,fee_atoms:accepted.fee_atoms})}
  if(url.pathname==='/submit-block'&&req.method==='POST'){const body=await readBody(req);let accepted;try{await serial(async()=>{const next=appendBlockFromSubmission(state,{header:body.header,nonce:Number(body.nonce),hash:String(body.hash||''),txids:(body.txids||[]).map(String)});state=next;accepted=tip(state);await persist()})}catch(error){const code=String(error.message).split(':')[0];return send(res,code==='stale_tip'?409:400,{ok:false,error:code,reason:code,height:tip(state)?.height||0,tip_hash:tip(state)?.hash||ZERO_HASH})}relay('/submit-block',{header:body.header,nonce:Number(body.nonce),hash:String(body.hash),txids:(body.txids||[]).map(String)}).catch(()=>{});return send(res,200,{ok:true,height:accepted.height,hash:accepted.hash,tx_count:accepted.txids.length})}
  if(url.pathname==='/peers')return send(res,200,{ok:true,network:NETWORK,upstream_api:UPSTREAM_API||null,peers:PEERS,feeds:FEEDS});
  return send(res,404,{ok:false,error:'not_found'});
}catch(error){console.error(error);return send(res,500,{ok:false,error:error.message||String(error)})}}

await loadState();
if(ENABLE_SYNC)await syncOnce().catch(()=>{});
const server=http.createServer((req,res)=>handler(req,res));
server.listen(PORT,HOST,()=>console.log(`[FAE] independent node ${NODE_VERSION} listening on http://${HOST}:${PORT} height=${state.chain.length}`));
if(ENABLE_SYNC)setInterval(()=>syncOnce().catch(()=>{}),SYNC_MS).unref();
