-- FAE public testnet v4 canonical database schema.
-- The browser never talks to these tables directly. The public Edge Function validates
-- protocol rules, then uses service_role to perform atomic state transitions.

create table if not exists public.fae_v4_blocks (
  height bigint primary key,
  hash text not null unique,
  previous_hash text not null,
  timestamp_ms bigint not null,
  difficulty_bits integer not null,
  nonce bigint not null,
  miner_address text not null,
  reward_atoms numeric(30,0) not null,
  header_json jsonb not null,
  created_at timestamptz not null default now(),
  txids jsonb not null default '[]'::jsonb
);

create table if not exists public.fae_v4_transactions (
  txid text primary key,
  network text not null,
  from_address text not null,
  public_key_spki text not null,
  signature text not null,
  inputs jsonb not null,
  outputs jsonb not null,
  fee_atoms numeric(30,0) not null default 0,
  status text not null default 'pending' check (status in ('pending','confirmed')),
  confirmed_height bigint,
  created_at timestamptz not null default now(),
  mempool_seq bigint generated by default as identity
);

create table if not exists public.fae_v4_utxos (
  outpoint text primary key,
  address text not null,
  amount_atoms numeric(30,0) not null,
  created_height bigint not null references public.fae_v4_blocks(height),
  spent boolean not null default false,
  created_at timestamptz not null default now(),
  spent_by text
);

create table if not exists public.fae_v4_mempool_spends (
  outpoint text primary key,
  txid text not null references public.fae_v4_transactions(txid) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.fae_v4_mempool_outputs (
  outpoint text primary key,
  txid text not null references public.fae_v4_transactions(txid) on delete cascade,
  output_index integer not null,
  address text not null,
  amount_atoms numeric(30,0) not null check (amount_atoms > 0),
  created_at timestamptz not null default now(),
  unique(txid,output_index)
);

create index if not exists fae_v4_transactions_from_idx on public.fae_v4_transactions(from_address,created_at desc);
create unique index if not exists fae_v4_transactions_mempool_seq_uq on public.fae_v4_transactions(mempool_seq);
create index if not exists fae_v4_transactions_status_created_idx on public.fae_v4_transactions(status,created_at);
create index if not exists fae_v4_utxos_address_idx on public.fae_v4_utxos(address) where spent=false;
create index if not exists fae_v4_utxos_address_spent_idx on public.fae_v4_utxos(address,spent,created_height);

alter table public.fae_v4_blocks enable row level security;
alter table public.fae_v4_transactions enable row level security;
alter table public.fae_v4_utxos enable row level security;
alter table public.fae_v4_mempool_spends enable row level security;
alter table public.fae_v4_mempool_outputs enable row level security;

revoke all on public.fae_v4_blocks from anon, authenticated;
revoke all on public.fae_v4_transactions from anon, authenticated;
revoke all on public.fae_v4_utxos from anon, authenticated;
revoke all on public.fae_v4_mempool_spends from anon, authenticated;
revoke all on public.fae_v4_mempool_outputs from anon, authenticated;

grant select,insert,update,delete on public.fae_v4_blocks to service_role;
grant select,insert,update,delete on public.fae_v4_transactions to service_role;
grant select,insert,update,delete on public.fae_v4_utxos to service_role;
grant select,insert,update,delete on public.fae_v4_mempool_spends to service_role;
grant select,insert,update,delete on public.fae_v4_mempool_outputs to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function public.fae_v4_guard_tx_content_immutable()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if new.txid is distinct from old.txid
     or new.network is distinct from old.network
     or new.from_address is distinct from old.from_address
     or new.public_key_spki is distinct from old.public_key_spki
     or new.signature is distinct from old.signature
     or new.inputs is distinct from old.inputs
     or new.outputs is distinct from old.outputs
     or new.fee_atoms is distinct from old.fee_atoms
     or new.created_at is distinct from old.created_at then
    raise exception 'FAE transaction content is immutable';
  end if;
  if old.status='confirmed' and (new.status is distinct from old.status or new.confirmed_height is distinct from old.confirmed_height) then
    raise exception 'confirmed FAE transaction state is immutable';
  end if;
  if old.status='pending' and new.status not in ('pending','confirmed') then
    raise exception 'invalid FAE transaction status transition';
  end if;
  if old.status='pending' and new.status='confirmed' and new.confirmed_height is null then
    raise exception 'confirmed transaction requires height';
  end if;
  return new;
end
$$;

drop trigger if exists fae_v4_tx_content_immutable on public.fae_v4_transactions;
create trigger fae_v4_tx_content_immutable
before update on public.fae_v4_transactions
for each row execute function public.fae_v4_guard_tx_content_immutable();

create or replace function public.fae_v4_accept_tx(
  p_txid text,
  p_network text,
  p_from_address text,
  p_public_key_spki text,
  p_signature text,
  p_inputs jsonb,
  p_outputs jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_input_sum numeric(30,0) := 0;
  v_output_sum numeric(30,0) := 0;
  v_outpoint text;
  v_amount numeric(30,0);
  v_address text;
  v_o jsonb;
  v_idx integer := 0;
begin
  if p_network <> 'fairyelf-public-testnet-v4' then return jsonb_build_object('ok',false,'reason','wrong_network'); end if;
  if jsonb_typeof(p_inputs) <> 'array' or jsonb_array_length(p_inputs)=0 or jsonb_array_length(p_inputs)>64 then return jsonb_build_object('ok',false,'reason','bad_inputs'); end if;
  if jsonb_typeof(p_outputs) <> 'array' or jsonb_array_length(p_outputs)=0 or jsonb_array_length(p_outputs)>16 then return jsonb_build_object('ok',false,'reason','bad_outputs'); end if;
  if exists(select 1 from public.fae_v4_transactions where txid=p_txid) then return jsonb_build_object('ok',false,'reason','duplicate_txid'); end if;

  for v_outpoint in select jsonb_array_elements_text(p_inputs)
  loop
    v_amount := null; v_address := null;
    select u.amount_atoms,u.address into v_amount,v_address
      from public.fae_v4_utxos u
      where u.outpoint=v_outpoint and u.spent=false
      for update;
    if not found then
      select m.amount_atoms,m.address into v_amount,v_address
        from public.fae_v4_mempool_outputs m
        where m.outpoint=v_outpoint
        for update;
    end if;
    if v_amount is null then return jsonb_build_object('ok',false,'reason','missing_or_spent_input','outpoint',v_outpoint); end if;
    if v_address <> p_from_address then return jsonb_build_object('ok',false,'reason','input_not_owned','outpoint',v_outpoint); end if;
    if exists(select 1 from public.fae_v4_mempool_spends where outpoint=v_outpoint) then return jsonb_build_object('ok',false,'reason','input_reserved','outpoint',v_outpoint); end if;
    v_input_sum := v_input_sum + v_amount;
  end loop;

  for v_o in select * from jsonb_array_elements(p_outputs)
  loop
    if not (v_o ? 'address') or not (v_o ? 'amount_atoms') then return jsonb_build_object('ok',false,'reason','bad_output'); end if;
    begin v_amount := (v_o->>'amount_atoms')::numeric; exception when others then return jsonb_build_object('ok',false,'reason','bad_output_amount'); end;
    if v_amount <= 0 then return jsonb_build_object('ok',false,'reason','bad_output_amount'); end if;
    v_output_sum := v_output_sum + v_amount;
  end loop;
  if v_output_sum > v_input_sum then return jsonb_build_object('ok',false,'reason','overspend'); end if;

  insert into public.fae_v4_transactions(txid,network,from_address,public_key_spki,signature,inputs,outputs,fee_atoms)
  values(p_txid,p_network,p_from_address,p_public_key_spki,p_signature,p_inputs,p_outputs,v_input_sum-v_output_sum);
  insert into public.fae_v4_mempool_spends(outpoint,txid)
    select value,p_txid from jsonb_array_elements_text(p_inputs);
  v_idx := 0;
  for v_o in select * from jsonb_array_elements(p_outputs)
  loop
    insert into public.fae_v4_mempool_outputs(outpoint,txid,output_index,address,amount_atoms)
      values(p_txid||':'||v_idx::text,p_txid,v_idx,v_o->>'address',(v_o->>'amount_atoms')::numeric);
    v_idx := v_idx + 1;
  end loop;
  return jsonb_build_object('ok',true,'txid',p_txid,'fee_atoms',(v_input_sum-v_output_sum)::text);
exception when unique_violation then
  return jsonb_build_object('ok',false,'reason','race_or_duplicate');
end
$$;

create or replace function public.fae_v4_accept_block_v2(
  p_height bigint,
  p_hash text,
  p_previous_hash text,
  p_timestamp_ms bigint,
  p_difficulty_bits integer,
  p_nonce bigint,
  p_miner_address text,
  p_reward_atoms numeric,
  p_header_json jsonb,
  p_txids jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_tip_height bigint; v_tip_hash text; v_txid text; v_tx record; v_outpoint text;
  v_o jsonb; v_idx integer; v_amount numeric(30,0);
begin
  perform pg_advisory_xact_lock(44004);
  select height,hash into v_tip_height,v_tip_hash from public.fae_v4_blocks order by height desc limit 1;
  if coalesce(v_tip_height,0)+1<>p_height or coalesce(v_tip_hash,repeat('0',64))<>p_previous_hash then
    return jsonb_build_object('ok',false,'reason','race_lost','height',coalesce(v_tip_height,0));
  end if;
  if exists(select 1 from public.fae_v4_blocks where height=p_height or hash=p_hash) then return jsonb_build_object('ok',false,'reason','duplicate_block'); end if;

  insert into public.fae_v4_blocks(height,hash,previous_hash,timestamp_ms,difficulty_bits,nonce,miner_address,reward_atoms,header_json,txids)
  values(p_height,p_hash,p_previous_hash,p_timestamp_ms,p_difficulty_bits,p_nonce,p_miner_address,p_reward_atoms,p_header_json,p_txids);

  for v_txid in select jsonb_array_elements_text(p_txids)
  loop
    select * into v_tx from public.fae_v4_transactions where txid=v_txid and status='pending' for update;
    if not found then return jsonb_build_object('ok',false,'reason','tx_not_pending','txid',v_txid); end if;
    for v_outpoint in select jsonb_array_elements_text(v_tx.inputs)
    loop
      if not exists(select 1 from public.fae_v4_mempool_spends where outpoint=v_outpoint and txid=v_txid) then return jsonb_build_object('ok',false,'reason','reservation_missing','txid',v_txid); end if;
      update public.fae_v4_utxos set spent=true,spent_by=v_txid where outpoint=v_outpoint and spent=false;
      if not found then
        if exists(select 1 from public.fae_v4_mempool_outputs where outpoint=v_outpoint) then
          return jsonb_build_object('ok',false,'reason','parent_not_materialized','txid',v_txid,'outpoint',v_outpoint);
        end if;
        return jsonb_build_object('ok',false,'reason','input_already_spent','txid',v_txid);
      end if;
    end loop;
    v_idx := 0;
    for v_o in select * from jsonb_array_elements(v_tx.outputs)
    loop
      v_amount := (v_o->>'amount_atoms')::numeric;
      delete from public.fae_v4_mempool_outputs where outpoint=v_txid||':'||v_idx::text;
      insert into public.fae_v4_utxos(outpoint,address,amount_atoms,created_height,spent)
      values(v_txid||':'||v_idx::text,v_o->>'address',v_amount,p_height,false);
      v_idx := v_idx + 1;
    end loop;
    update public.fae_v4_transactions set status='confirmed',confirmed_height=p_height where txid=v_txid;
    delete from public.fae_v4_mempool_spends where txid=v_txid;
  end loop;

  insert into public.fae_v4_utxos(outpoint,address,amount_atoms,created_height,spent)
  values(p_hash||':0',p_miner_address,p_reward_atoms,p_height,false);
  return jsonb_build_object('ok',true,'height',p_height,'hash',p_hash,'tx_count',jsonb_array_length(p_txids));
exception when unique_violation then
  return jsonb_build_object('ok',false,'reason','race_lost');
end
$$;

revoke all on function public.fae_v4_guard_tx_content_immutable() from public;
revoke all on function public.fae_v4_accept_tx(text,text,text,text,text,jsonb,jsonb) from public;
revoke all on function public.fae_v4_accept_block_v2(bigint,text,text,bigint,integer,bigint,text,numeric,jsonb,jsonb) from public;
grant execute on function public.fae_v4_accept_tx(text,text,text,text,text,jsonb,jsonb) to service_role;
grant execute on function public.fae_v4_accept_block_v2(bigint,text,text,bigint,integer,bigint,text,numeric,jsonb,jsonb) to service_role;
